server:
  port: 8910
adminRPC:
  socket: /mnt/solana-ledger/admin.rpc
sources:
  - name: bootstrap
    file: /var/log/cloud-init.log
  - name: validator
    file: /mnt/logs/solana-validator.log
    filters:
      - "solana_metrics::metrics"